In [ ]:
!pip install -q transformers datasets evaluate accelerate scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.4 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import torch
import numpy as np
import evaluate
from google.colab import drive
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

drive.mount('/content/drive')
output_directory = '/content/drive/MyDrive/finbert_finetuned'

Mounted at /content/drive

In [ ]:
df_extracted_edgar_china_sentences = pd.read_excel('/content/drive/MyDrive/EDGAR/extracted_edgar_china_sentences.xlsx')
display(df_extracted_edgar_china_sentences.head())

,ticker,year,document_type,sentence,filename
0,AMD,2020,10-K,We conduct product and system research and dev...,mda_2020_10-K_0000002488-20-000008.txt.txt
1,AMD,2020,10-K,"For example, the European Union (EU) and China...",mda_2020_10-K_0000002488-20-000008.txt.txt
2,AMD,2020,10-K,"A number of jurisdictions including the EU, Au...",mda_2020_10-K_0000002488-20-000008.txt.txt
3,AMD,2022,10-K,We conduct product and system research and dev...,mda_2022_10-K_0000002488-22-000016.txt.txt
4,AMD,2022,10-K,"For example, the European Union (EU) and China...",mda_2022_10-K_0000002488-22-000016.txt.txt

In [ ]:
df_extracted_earnings_china_sentences = pd.read_excel('/content/drive/MyDrive/EarningsCall/extracted_earnings_china_sentences.xlsx')
display(df_extracted_earnings_china_sentences.head())

,ticker,year,document_type,sentence,filename
0,TER,2015,EarningsCall,"So one of the factors there will be in Asia, a...",20150129_Teradyne_Inc.txt
1,TER,2017,EarningsCall,"On the other end, you have emerging companies,...",20170126_Teradyne_Inc.txt
2,TER,2017,EarningsCall,"And then, I guess just tied to that, also, how...",20170126_Teradyne_Inc.txt
3,TER,2017,EarningsCall,"Obviously, we hear a lot of investment on the ...",20170126_Teradyne_Inc.txt
4,TER,2017,EarningsCall,Just curious how you're positioned in China an...,20170126_Teradyne_Inc.txt

In [ ]:
df_extracted_edgar_earnings_china_sentences = pd.concat([
    df_extracted_edgar_china_sentences,
    df_extracted_earnings_china_sentences
], ignore_index=True)

display(df_extracted_edgar_earnings_china_sentences.head())

,ticker,year,document_type,sentence,filename
0,AMD,2020,10-K,We conduct product and system research and dev...,mda_2020_10-K_0000002488-20-000008.txt.txt
1,AMD,2020,10-K,"For example, the European Union (EU) and China...",mda_2020_10-K_0000002488-20-000008.txt.txt
2,AMD,2020,10-K,"A number of jurisdictions including the EU, Au...",mda_2020_10-K_0000002488-20-000008.txt.txt
3,AMD,2022,10-K,We conduct product and system research and dev...,mda_2022_10-K_0000002488-22-000016.txt.txt
4,AMD,2022,10-K,"For example, the European Union (EU) and China...",mda_2022_10-K_0000002488-22-000016.txt.txt

In [ ]:
model_name = "ProsusAI/finbert"

print("Loading tokenizer and model...")
tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    ignore_mismatched_sizes=True
)

Loading tokenizer and model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
def get_sentiment_scores(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
    outputs = model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    score = probs.detach().numpy()[0]
    predicted_class_id = probs.argmax().item()
    predicted_label = model.config.id2label[predicted_class_id]

    print(f"Text: {text}\nScore: {score}\nLabel: {predicted_label}")
    return predicted_label

In [ ]:
df_extracted_edgar_earnings_china_sentences['score'] = df_extracted_edgar_earnings_china_sentences['sentence'].apply(get_sentiment_scores)
display(df_extracted_edgar_earnings_china_sentences.head())

Streaming output truncated to the last 5000 lines.
Text: And that was very helpful in that environment
that we experienced here in China last year.
Score: [0.8745321  0.00930792 0.11615995]
Label: positive
Text: And similar to China, we also have a very strong execution by our sales and marketing
organization in Europe.
Score: [0.89681274 0.00724187 0.09594535]
Label: positive
Text: I guess first Olivier, based on the feedback you're
hearing from either internally or externally how confident are you at this point that things get
going again next Monday in China?
Score: [0.20637512 0.01338455 0.78024036]
Label: neutral
Text: It's -- even an area that we right now see in our Chinese business.
Score: [0.08269633 0.01359402 0.90370965]
Label: neutral
Text: A - `Shawn P. Vadala, Chief Financial Officer `
Yes, we might see something in field service but that's a smaller part of the Chinese business
versus our global average.
Score: [0.11952638 0.01888832 0.86158526]
Label: neutral
Text: And then this might be hard to do, but given coronavirus is kind of impacting a lot of
things outside of China, but is it possible to kind of step back from coronavirus and say, you've
been pretty consistent since last year flagging these uncertainties and some pockets of
weakness, but we have seen PMIs tick up a little bit here.
Score: [0.48434788 0.4182337  0.09741837]
Label: positive
Text: However, we remain cautious
on the global economy, as we see continued uncertainties, for example in the Chinese end
markets, industrial end markets, some questions on Europe, and in general, we face tougher
comps, particularly in the second half of the year.
Score: [0.14236198 0.77604556 0.08159243]
Label: negative
Text: Core Industrial did better than we expected, with growth in low single-digits, driven by strong
growth in Asia, including China.
Score: [0.9575614  0.017745   0.02469369]
Label: positive
Text: China did better than expected with 15% growth in the quarter.
Score: [0.95410883 0.02162188 0.02426917]
Label: positive
Text: Lab in China continued to
do very well, and we were very pleased to see strong growth in Industrial in the quarter.
Score: [0.9553218  0.01785315 0.02682507]
Label: positive
Text: And then also was wondering if you could give some color on emerging market
demand, excluding China, and whether FX settling down a bit is helping demand?
Score: [0.19581331 0.03751882 0.76666784]
Label: neutral
Text: Also, outside of China we had, for example,
Southeast Asia that did very well.
Score: [0.76985186 0.01321632 0.2169318 ]
Label: positive
Text: Want to spend a minute on emerging markets,
specifically if you could just kind of compare and contrast what you're seeing in South America
versus China?
Score: [0.07327113 0.02663177 0.90009713]
Label: neutral
Text: I know you have a much bigger business in China, but we don't have a lot of
visibility, I think in the last couple of weeks here, in terms of other companies in the space talking
about how the year closed out between emerging markets versus – I mean in China versus South
America.
Score: [0.11779297 0.0314121  0.8507949 ]
Label: neutral
Text: A - `Olivier A. Filliol, President and Chief Executive Officer `
Two very different situations in the sense that China, the microenvironment and the macro trends
are very favorable for us.
Score: [0.2174875  0.02610969 0.7564028 ]
Label: neutral
Text: In Q4 we have seen that the industrial business started to pick up also for us in China.
Score: [0.942682   0.01389204 0.0434259 ]
Label: positive
Text: At China, it seems to be a
more steady opportunity to build.
Score: [0.83056635 0.00934643 0.1600872 ]
Label: positive
Text: And again, I want to specify that we had different product
categories in China that continue to do very well across many quarters.
Score: [0.44372824 0.01496348 0.5413083 ]
Label: neutral
Text: And then on China.
Score: [0.03175808 0.03541487 0.93282706]
Label: neutral
Text: Can you talk through the backlog or give us some color on in core industrial in China,
where you're continuing to potentially see weakness despite the strong 4Q?
Score: [0.28376648 0.22434899 0.49188456]
Label: neutral
Text: A - `William P. Donnelly, Executive Vice President `
So in terms of our industrial business in China, I think that you very much see this just the impact
of comps getting easier and some of the really difficult markets related to infrastructure have just
shrunk as a percentage of total sales for us.
Score: [0.16386794 0.6054346  0.23069753]
Label: negative
Text: And so if you were to, I'm kind of oversimplifying
now, if you were to bifurcate our performance the last couple years in China, you would say we
had some good markets that were growing mid to high-single-digits and we had some bad
markets that in many cases were down more than double-digits.
Score: [0.05779147 0.84907526 0.09313326]
Label: negative
Text: We probably see
more than any other market how when credit availability changes in China, it has a little faster
impact on – it can be more volatile itself, availability, and it tends to have a pretty fast impact in
the market.
Score: [0.19765316 0.05552771 0.7468191 ]
Label: neutral
Text: So when you hear us sometimes talk cautiously about the future in China, it's probably less about
our competitive position or what we think can happen long term for China, but more about some
of these shorter-term topics.
Score: [0.05850474 0.03908226 0.9024131 ]
Label: neutral
Text: Q - `Rick C. Eastman, Analyst, Robert W. Baird & Co., Inc. (Broker) `
Bill, just on the back of that last response to the core China strength, you did touch on credit
there and the sensitivity of the core industrial in China to credit.
Score: [0.8759191  0.02067485 0.10340612]
Label: positive
Text: When, I think what you might be referring to
a little bit, Rick, is the idea of getting cash out of China.
Score: [0.09115475 0.0302852  0.87856   ]
Label: neutral
Text: It's not much different than what we've had in China for a long period of time.
Score: [0.11084621 0.01936835 0.8697855 ]
Label: neutral
Text: So but against the China industrial comps then as we roll into 2017, again, a high-single-digit
growth, maybe even double-digit, with that credit background would be a decent assumption?
Score: [0.35927624 0.01547736 0.6252464 ]
Label: neutral
Text: We probably internally our guys would think they can do better than that, but
we think it's prudent to discount it for these things you hear me constantly bringing up, the risk
around overcapacity and credit in China.
Score: [0.18243548 0.04475516 0.7728094 ]
Label: neutral
Text: And is the product inspection business in China – where does that stand as a percentage of
your China sales?
Score: [0.03203689 0.03060303 0.9373601 ]
Label: neutral
Text: Local-currency sales increased 11% in China in the quarter.
Score: [0.95827794 0.0155756  0.02614647]
Label: positive
Text: Local-currency sales increased 14% in China in 2022.
Score: [0.94853145 0.01231375 0.03915488]
Label: positive
Text: Finally, Food Retail delivered very strong growth with project activities in the
Americas and Europe, offset in-part by a significant sales decline in China due to disruptions from
the pandemic.
Score: [0.9495622  0.03310895 0.01732881]
Label: positive
Text: And finally, Asia and the Rest of the World had another quarter of
good growth led by our Lab business, China grew 11% with a particular strong growth in Lab.Switching now to our Service business, we continue to see excellent momentum and service
sales grew 11% in the quarter and 12% for the year.
Score: [0.9572767  0.01530531 0.02741808]
Label: positive
Text: And then, for China, we're looking at mid-single-digit growth for Q1 and high-
single-digit growth for the full-year.
Score: [0.17434238 0.02106342 0.80459416]
Label: neutral
Text: Shawn, maybe just on your last point there on China, can
you just talk a little bit about the transition from first-half of the year, headwinds from COVID, to
something that looks like presumably a step-up in the back-half of the year?
Score: [0.10557243 0.02098509 0.8734425 ]
Label: neutral
Text: I'd be particularlyinterested in your thoughts around stimulus dollars in China, some of our companies have just
been more emphatic about the impact there that you might be than others, so would just love
you get your two cents.
Score: [0.07916445 0.05377204 0.8670635 ]
Label: neutral
Text: So, one, we're very pleased with the quarter
we're coming off, 11% growth in China.
Score: [0.9493474  0.01595544 0.03469723]
Label: positive
Text: And then, when we look at China for 2023, we feel very
good about.
Score: [0.23140599 0.01285891 0.7557351 ]
Label: neutral
Text: We've always said that things can change quickly in China,
and this is another example with the reopening.
Score: [0.16839506 0.02222287 0.8093821 ]
Label: neutral
Text: Of course, they just also came off the Chinese New Year as well.
Score: [0.09946007 0.09374585 0.8067941 ]
Label: neutral
Text: So, we continue to feel like we're very well-positioned for
China for the medium-to-long term.
Score: [0.89114517 0.00886368 0.09999122]
Label: positive
Text: Again, we've a strong team in China.
Score: [0.9217828  0.01004845 0.0681687 ]
Label: positive
Text: Obviously in China, team
is good very well, using the same go-to-market strategies and tools that we use in the rest of the
world, very efficiently.
Score: [0.843421   0.00775213 0.1488269 ]
Label: positive
Text: As said here, I'm very confident about the mid and long-term performance
in China.
Score: [0.8494386  0.0159138  0.13464767]
Label: positive
Text: The area -- the region where we had probably still more happened was also in China given
COVID-19.
Score: [0.06053827 0.01819677 0.921265  ]
Label: neutral
Text: Could you just split out Lab versus
Industrial in China in the quarter?
Score: [0.05310199 0.03706201 0.909836  ]
Label: neutral
Text: China is a big part of this business.
Score: [0.04330923 0.02024459 0.9364462 ]
Label: neutral
Text: And multispecialty
growth in Korea and China.
Score: [0.7036841  0.01062125 0.2856947 ]
Label: positive
Text: And China were healthy through the year.
Score: [0.92399734 0.03856293 0.0374397 ]
Label: positive
Text: As we have said in prior calls, system quotas in China and reimbursements in Japan
temper placement growth and make it hard to predict.
Score: [0.01409503 0.95455366 0.03135135]
Label: negative
Text: The decrease
in system placements relative to the prior year reflected 10 fewer systems into China, where we
await a new quota.
Score: [0.02999645 0.9514773  0.01852622]
Label: negative
Text: Current-quarter systems sales included 26 into Europe, three into China, 15 into Japan.
Score: [0.09552785 0.0177018  0.88677037]
Label: neutral
Text: Total procedure growth in Asia overall was strong, notably so in key strategic markets of China,
Japan.
Score: [0.9589112  0.01554796 0.02554089]
Label: positive
Text: Our 2017 procedure growth expectations are directionally lower than the 2016 results, based
upon the following assumptions for 2017 -- moderating growth in our mature US dVP and
gynecology procedures that benefited from favorable macro trends in 2016, moderating
international procedure growth as we await additional da Vinci procedure reimbursement in
Japan and additional system sales quota in China.
Score: [0.77877855 0.16558059 0.05564085]
Label: positive
Text: Q - `Tao Levy, Analyst, Wedbush Securities `
Just maybe you could update us on the status of China and the quota, next steps there, as well
as what is needed to get the Xi approved in China.
Score: [0.1482647  0.00956059 0.84217477]
Label: neutral
Text: On the quota side, the quota is dependent upon the approval
of their budget, the Chinese government budget.
Score: [0.02488829 0.05009443 0.9250173 ]
Label: neutral
Text: I don't see a major impediment to Xi clearance in China.
Score: [0.09481256 0.0916835  0.813504  ]
Label: neutral
Text: And in general
we are encouraged by the response of the market to robotic surgery and to Intuitive in China.
Score: [0.82149255 0.00728011 0.17122738]
Label: positive
Text: So I guess in the case where your European procedure -- or system sales don't pick up again and
maybe the China tender or the China quota doesn't come on board as quickly as you expect,
what is the risk to that international procedure growth of 20% plus?
Score: [0.07067513 0.02698361 0.90234125]
Label: neutral
Text: Internationally, I think the areas I pointed out specifically were for
China.
Score: [0.08614341 0.01575909 0.8980975 ]
Label: neutral
Text: The fact is that the systems we do have in
China are some of the (technical difficulty) productive systems we have.
Score: [0.04794302 0.31520504 0.63685197]
Label: neutral
Text: Our efforts in China will accelerate in 2019 with
the da Vinci distribution arm of Fosun Pharma, Chindex, joining our joint venture this quarter.
Score: [0.89891297 0.0085146  0.09257246]
Label: positive
Text: Combined with the release of the next system quota and the clearance of da Vinci Xi in China,
we will be accelerating investments to establish our base to serve China over the long term.
Score: [0.90710306 0.00894007 0.08395683]
Label: positive
Text: In 2018, we also acquired our da Vinci business in India and Taiwan, and anticipate strengthening
our investments and presence over the next several quarters.
Score: [0.94799536 0.01127313 0.04073142]
Label: positive
Text: As described above, the increase in spend is driven primarily
by funding and growth of our joint venture in China, the ramp of our informatics efforts,
infrastructure to support our procedure growth, including manufacturing lines and facilities, and
the launch of our new platforms.
Score: [0.87945724 0.0074216  0.11312117]
Label: positive
Text: Instrument and accessory revenue of $539 million increased 18% with last year, which is lower
than procedure growth, reflecting approximately 6 million of I&A repurchased from distributors in
China and Taiwan in conjunction with transactions to go direct in both geographies and customer
buying patterns, partially offset by increased usage of our advanced instruments.
Score: [0.6720094  0.2920875  0.03590314]
Label: positive
Text: Instrument and
accessory revenue realized per procedure was approximately $1,890, a decrease of 1%
compared with the fourth quarter of 2017 and relatively unchanged compared with last quarter.Excluding the buyback of inventory from China and Taiwan, instrument and accessory revenue per
procedure was similar to last year.
Score: [0.02828012 0.9500243  0.02169569]
Label: negative
Text: The increase in fourth quarter expenses reflect, one,
increased costs that fluctuate directly with revenue, including sales and corporate incentive
compensation; two, costs we elected to accelerate, including spend on infrastructure in order to
scale the business; and three, investments to drive our future opportunity, including costs
associated with going direct in China, Taiwan, India, and cost of prototypes.
Score: [0.7894994  0.07632751 0.1341731 ]
Label: positive
Text: We will accelerate spending on our informatics capabilities; expansion of our OUS
markets, including China, India, and Taiwan; and investments that enable us to scale the business,
including expansion of in automation of manufacturing.
Score: [0.89662457 0.00733772 0.09603772]
Label: positive
Text: Procedure growth in China again moderated in Q4, as da Vinci
system capacity expansion was constrained by system quota requirements.
Score: [0.5009247  0.4728898  0.02618554]
Label: positive
Text: The elements of SG&A are, as I discussed, the expansion OUS and the
investments we're making in China, India, and Taiwan.
Score: [0.08086318 0.01019473 0.90894204]
Label: neutral
Text: I was wondering if you could kind of lay out how much of that is the investment in
China and Taiwan in going direct.
Score: [0.0394114  0.02076002 0.9398286 ]
Label: neutral
Text: There is a chunk of spending associated with the expansion OUS in
China, India, and Taiwan.
Score: [0.12522598 0.02783746 0.8469365 ]
Label: neutral
Text: And then if I could just ask one last one on the cadence of placements in China you're
expecting, now that you've had a little bit of time to digest the quota, anything to think about in
the first half of the year here?
Score: [0.04227087 0.02767392 0.9300552 ]
Label: neutral
Text: If there were to be competitors that got their product approved in China, they
would share in that quota.
Score: [0.2037675  0.00995405 0.7862784 ]
Label: neutral
Text: What I would say – and finally, the other implication is that there is a 25% tariff on the
robots that the Chinese have imposed.
Score: [0.0959622  0.02063598 0.8834018 ]
Label: neutral
Text: We think that there is high interest in robotics in China, so
I don't know how that 25% will affect their desire to buy.
Score: [0.2736084  0.02016615 0.70622545]
Label: neutral
Text: Maybe turning back to the acquisition of your da Vinci business in India and
Taiwan again.
Score: [0.1003733  0.01092252 0.8887041 ]
Label: neutral
Text: I'd be curious to hear more about your thoughts about the relative size of the opportunities in
India and Taiwan.
Score: [0.12738399 0.00995899 0.862657  ]
Label: neutral
Text: Sort of you mentioned Japan as a proxy a little bit, but do India and Taiwan
matchup with China and Japan in terms of magnitude?
Score: [0.08219306 0.01590565 0.90190125]
Label: neutral
Text: Just maybe help us think about that and frame it for us.Clearly, the strategic motivation behind India and Taiwan are a little bit different.
Score: [0.0745385  0.03387917 0.89158237]
Label: neutral
Text: With regard to
Taiwan, in terms of actual size (00:55:27), it's not going to be a huge part of the business.
Score: [0.03707017 0.03571665 0.9272132 ]
Label: neutral
Text: But the range will be largely
– the range itself is largely reflective – the biggest factor is going to be the breadth and pace of
growth in U.S. general surgery, our largest category now, than the mature procedures and some
other factors regarding growth in China, timing of placements of new systems, and the pace of
adoption of reimbursed procedures in Japan.
Score: [0.18450359 0.01033774 0.80515873]
Label: neutral
Text: In China, we saw accelerated customer acceptance of
our partnership with Fosun Pharma and our products with growth and procedures and the
business overall outpacing our pre-pandemic plans.
Score: [0.9582405  0.01565332 0.02610616]
Label: positive
Text: In 2020, China emerged as our number two
procedure market.
Score: [0.46973935 0.01027017 0.51999044]
Label: neutral
Text: While the
impact of COVID on procedures in the Asia-Pacific region, including China, Japan and Korea wasfar less significant.
Score: [0.07904192 0.83787763 0.08308044]
Label: negative
Text: The
decrease relative to last year reflects a lower mix of systems placed in China and Japan in a
higher proportion of trade transactions.
Score: [0.02316938 0.95134294 0.0254878 ]
Label: negative
Text: Current quarter system placements included 54 into Europe, 22 into Japan
and 13 into China compared with 54 into Europe, 26 into Japan and 39 into China in the fourth
quarter of 2019.System placements into China In the fourth quarter of 2019 were higher as hospitals accelerated
tenders in anticipation of the possibility of higher tariffs.
Score: [0.9490755  0.02725711 0.02366732]
Label: positive
Text: With respect to key contributors to growth, overall procedures in China and bariatrics in the US
were the largest drivers of procedure growth in Q4.
Score: [0.6234087  0.01268391 0.36390746]
Label: positive
Text: In China, procedure
growth accelerated as new systems installed under the quota begin to provide additional
capacity for incremental growth.
Score: [0.9387735  0.01180272 0.04942374]
Label: positive
Text: Q4 China procedures had broad-based growth in urology,
thoracic, general surgery and gynecology.
Score: [0.8088607  0.01471799 0.17642123]

,ticker,year,document_type,sentence,filename,score
0,AMD,2020,10-K,We conduct product and system research and dev...,mda_2020_10-K_0000002488-20-000008.txt.txt,neutral
1,AMD,2020,10-K,"For example, the European Union (EU) and China...",mda_2020_10-K_0000002488-20-000008.txt.txt,neutral
2,AMD,2020,10-K,"A number of jurisdictions including the EU, Au...",mda_2020_10-K_0000002488-20-000008.txt.txt,neutral
3,AMD,2022,10-K,We conduct product and system research and dev...,mda_2022_10-K_0000002488-22-000016.txt.txt,neutral
4,AMD,2022,10-K,"For example, the European Union (EU) and China...",mda_2022_10-K_0000002488-22-000016.txt.txt,neutral

In [ ]:
df_extracted_edgar_earnings_china_sentences.to_excel('extracted_edgar_earnings_china_sentences.xlsx', index=False)
print("File saved successfully.")

File saved successfully.